### ISSUE TITLE
index.js

### ISSUE THREAD

**Issue by qxl1231** [MiceLiD/ofo-applet#1]
// 地图标记点击事件，连接用户位置和点击的单车位置
  bindmarkertap: function(e){
    let _markers = this.data.markers;
    let markerId = e.markerId;
    let currMaker = _markers[markerId];

这个里的e.markerId 是在前端页面点击赋值的把,_markers[markerId]; 经常会出现报错,这个id 我看了,不是数组下标值哦>?求解一下

**Comment by lidongsevenlee** [comment]
点击标记点将返回标记点的id,我在后端定义了每个标记点的id（0-7），所以，这里点击相应的标记，将返回（0-7）中的某个数。_markers[markerId]表示当前点击的标记，这里要用它和起始位置连线

**Comment by qxl1231** [comment]
![image](https://cloud.githubusercontent.com/assets/8305742/26520010/036071ac-42fd-11e7-82e1-c4bc6173c0d4.png)
如图,我定了3个markers,但是返回的markerId居然是16?我不知道这个16从哪里来的?>

**Comment by 4what2do** [comment]
真机看不到覆盖物？
